import { promises as fs } from "fs";
import path from "path";

// ── Read source tokens ─────────────────────────────────────────────────────
const raw = JSON.parse(await fs.readFile("tokens/figma-variables.json", "utf-8"));

// ── Helpers ────────────────────────────────────────────────────────────────
const toKebab = (str) =>
  str
    .replace(/\//g, "-")
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/\s+/g, "-")
    .toLowerCase();

function flattenSection(obj, prefix = "") {
  const vars = [];
  for (const [key, value] of Object.entries(obj)) {
    const varName = prefix ? `${prefix}-${toKebab(key)}` : toKebab(key);
    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      vars.push(...flattenSection(value, varName));
    } else {
      vars.push([varName, value]);
    }
  }
  return vars;
}

// ── Build CSS sections ─────────────────────────────────────────────────────
const sections = {
  Colors:     "color",
  Typography: "typography",
  Radius:     "radius",
  Spacing:    "spacing",
  Shadows:    "shadow",
};

const lines = [
  "/* Auto-generated by GitHub Actions — do not edit manually */",
  ":root {",
];

for (const [sectionKey, cssPrefix] of Object.entries(sections)) {
  if (!raw[sectionKey]) continue;
  lines.push(`\n  /* ── ${sectionKey} ── */`);
  for (const [name, value] of flattenSection(raw[sectionKey])) {
    const cssVar = `--${cssPrefix}-${name}`;
    lines.push(`  ${cssVar}: ${value};`);
  }
}

lines.push("}");

// ── Write output ───────────────────────────────────────────────────────────
await fs.mkdir("build", { recursive: true });
await fs.writeFile("build/tokens.css", lines.join("\n") + "\n");

console.log(`Tokens built → build/tokens.css (${lines.length} lines)`);

