name: Sync Figma Variables

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - name: Sync Variables
        run: node scripts/sync-figma.js
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git diff --cached --quiet || (
            git commit -m "Update Figma variables"
            git push
          )
